apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  REDIS_HOST: redis
  CATALOGUE_HOST: catalogue
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    tire: backend
    component: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tire: backend
      component: cart
   #pod   
  template:
    metadata:
      labels:
        project: roboshop
        tire: backend
        component: cart
    spec:
      containers:
      - name: cart
        image: aravinddharla/cart:4.0.0
        envFrom:
        - configMapRef:
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  # service labeles
  labels:
    project: roboshop
    tire: backend
    component: cart
spec:
    # service uses the below labels to select the pods
  selector:
    project: roboshop
    tire: backend
    component: cart
  ports:
    - protocol: TCP
      port: 8080 #service port
      targetPort: 8080  #container port